"""Adiciona campos de pagamento ao orçamento

Revision ID: 51eaebd0c87f
Revises: 637cc36c5ebe
Create Date: 2025-05-13 15:45:58.605735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51eaebd0c87f'
down_revision = '637cc36c5ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bandeira_cartao', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parcelas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('taxa_cartao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_original', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.drop_column('valor_original')
        batch_op.drop_column('taxa_cartao')
        batch_op.drop_column('parcelas')
        batch_op.drop_column('bandeira_cartao')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
