"""Initial migration

Revision ID: 637cc36c5ebe
Revises: 
Create Date: 2025-05-12 20:02:52.761158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637cc36c5ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('marca_equipamento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacidade_btu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('validade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('convertido_servico', sa.Boolean(), nullable=True))
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('convertido_servico')
        batch_op.drop_column('validade')
        batch_op.drop_column('custo')
        batch_op.drop_column('capacidade_btu')
        batch_op.drop_column('marca_equipamento')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
